---
apiVersion: v1
kind: Service
metadata:
  name: carstore
  annotations:
    discovery.kuadrant.io/oas-configmap: "carstore-oas"
  labels:
    discovery.kuadrant.io/enabled: "true"
spec:
  selector:
    svc: cats
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: unprotected
spec:
  selector:
    svc: other
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
