# permissions for end users to edit gateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-editor-role
rules:
- apiGroups:
  - giggle.kuadrant.io
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - giggle.kuadrant.io
  resources:
  - gateways/status
  verbs:
  - get
